config/routes.rb
Rails.application.routes.draw do
  root  'pages#home'
  get   '/admin',                to: 'sessions#new'
  post  '/admin',                to: 'sessions#create'
  get   '/logout',               to: 'sessions#destroy'
  get   '/contact',              to: 'pages#contact'
  get   '/home',                 to: 'pages#home'
  get   '/gallery',              to: 'pages#gallery'
  get   '/peteliskes',           to: 'gallery#pete'
  get   '/kaspineliai_plaukams', to: 'gallery#kasp'
  get   '/medziagos',            to: 'gallery#med'

  resources :posts 
  resources :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  # Returns the hash digest of the given string.
  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # pirmas postas naujausias
  default_scope -> { order(created_at: :desc) }
  validates :picture, presence: true
  mount_uploader :picture, PictureUploader

  def next
     Post.where("id < ?", id).first
  end

  def previous
     Post.where("id > ?", id).order(id: :desc).last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
#  safe parameter
# allow nested params as array
  def post_params
    params.require(:post).permit(:content, :price, :purpose, :picture)
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController

  def pete
    @posts = Post.all
    @post = Post.new
    # pulling correct data
    @post_feed = @posts.where(purpose: "pete").paginate(page: params[:page], :per_page => 12)
    end

  def kasp
    @posts = Post.all
    @post = Post.new
    @post_feed = @posts.where(purpose: "kasp").paginate(page: params[:page], :per_page => 12)
  end

  def med
    @posts = Post.all
    @post = Post.new
    @post_feed = @posts.where(purpose: "med").paginate(page: params[:page], :per_page => 12)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def gallery
    @posts = Post.all
    @post = Post.new
    @post_feed = @posts.paginate(page: params[:page], :per_page => 12)
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # action can with posts can only be performed by admin
  before_action :logged_in_admin, only: [:create, :destroy, :edit, :update]
# post creation and failed save
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Pavyko įkelti"
      redirect_to gallery_url
    else
      flash[:danger] = "Nepavyko sukurti"
      redirect_to gallery_url
    end
  end

  # post show
  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Pataisyti pavyko!"
      redirect_to gallery_url
    else
      flash[:danger] = "Pataisyti nepavyko"
      rener 'edit'
    end
  end

# destroying post
  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Ištrintas"
    redirect_to gallery_url
  end


  private

# checking if you are logged in
  def logged_in_admin
    unless logged_in?
      flash[:danger] = "Prisijunkite"
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

    # sukurus admin per rails console, prisijungimo funkcija
  def create
    user = Admin.first
    if user.nil?
      flash.now[:danger] = "Nesukurtas administratorius"
      render 'new'
    elsif user.authenticate(params[:session][:password])
      log_in user
      redirect_to gallery_url
    else
      flash.now[:danger] = "Blogas slaptažodis"
      render 'new'
    end
  end

# atsijungimo funkcija
  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(admin)
    session[:admin_id] = admin.id
  end

  # Returns the current logged-in user (if any).
  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_admin.nil?
  end

  def log_out
    session.delete(:admin_id)
    @current_admin = nil
  end
end

app/views/gallery/_buttons.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <ul class="nav navbar-left" id="buttons">
      <li><%= link_to "Naujienos", gallery_url, class: 'btn btn-default' %></li>
      <li><%= link_to "Peteliškės", peteliskes_url, class: 'btn btn-default' %></li>
      <li><%= link_to "Kaspinėliai plaukams", kaspineliai_plaukams_url, class: 'btn btn-default' %></li>
      <li><%= link_to "Medžiagos", medziagos_url, class: 'btn btn-default' %></li>
    </ul>
  </div>
</nav>

app/views/gallery/kasp.html.erb
<h1>Kaspinėlių plaukams galerija</h1>
<%= render 'posts/posts_feed' %>

app/views/gallery/med.html.erb
<h1>Medžiagų galerija</h1>
<%= render 'posts/posts_feed' %>

app/views/gallery/pete.html.erb
<h1>Peteliškių galerija</h1>
<%= render 'posts/posts_feed' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Peteliškių namai Facebook",
                "https://www.facebook.com/peteliskiunamaii",
                target: :_bank %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Kontaktai", contact_url %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Peteliškių namai", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li><%= link_to "Atsijungti", logout_path, id: "navig" %></li>
            <% else %>
            <li><%= link_to "Administratoriaus priėjimas", admin_path, id: "navig" %></li>
            <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peteliskiu namai</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/header' %>
    <% unless action_name == "home" || action_name == "new" %>
    <div>
      <%= render 'gallery/buttons' %>
    </div>
    <% end %>
  </head>
  
  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
      <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/pages/contact.html.erb
<body>
<h1>Kontaktai</h1>
<article>
<h4><%= link_to "Tomas Žukauskas",
"https://www.facebook.com/tomas.zukauskas.735", target: :_bank %></h4>
  <p> El. paštas: zukausk.tomas@gmail.com<p>
  <p>Mobilusis numeris: +370 60434204</p>
</article>
</body>

app/views/pages/gallery.html.erb
<body>
<h1>Naujienos</h1>
<div>
<%= render 'posts/posts_feed' %>
<!-- as idiomatic as it gets -->
</div>
</body>

app/views/pages/home.html.erb
<h1><strong>Sveiki atvykę</strong></h1>
<div id="homelogo">
<%= link_to image_tag('Logo.jpg'), gallery_path %>
<%= link_to "Galerija", gallery_url, class: "btn btn-lg btn-default", id: "button" %>
</div>

app/views/posts/_post.html.erb
<div class="box">
  <span class="helper"></span>
  <%= link_to image_tag(post.picture.url), post %>
</div>

app/views/posts/_post_form.html.erb
<%= form_for(@post) do |f| %>
    <%= render 'pages/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Aprašykite peteliškę" %>
    </div>
    <div class="field">
      <%= f.text_area :price, placeholder: "Įrašykite kainą" %>
    </div>
    <span class="picture">
      <%= f.label "Nuotrauka:" %>
      <%= f.file_field :picture %>
    </span>
    <strong>Pasirinkite tipą:</strong>
    <div class="btn-group" data-toggle="buttons">
      <label class="btn btn-default ">
        <input type="radio" value='pete' name="post[purpose]" > Peteliškė
      </label>
      <label class="btn btn-default">
        <input type="radio" value='kasp' name="post[purpose]" > Kaspinėlis plaukams
      </label>
      <label class="btn btn-default">
        <input type="radio" value="med" name="post[purpose]" > Medžiaga
      </label>
    </div>
    <div class="submit">
    <%= f.submit "Talpinti", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_posts_feed.html.erb
<body>
<div class="container">
  <% if logged_in? %>
    <span class="post_form">
      <%= render 'posts/post_form' %>
    </span>
  <% end %>
  <div id="feed" class="wrapper">
    <% if @posts.any? %>
      <%= render @post_feed %>
    <% else %>
      <p>No posts yet</p>
    <% end %>
  </div>
</div>
<%= will_paginate @post_feed, :previous_label => '<', :next_label => '>' %>
</body>

app/views/posts/edit.html.erb
<h1>Tvarkymas</h1>
<div class="row">
  <aside class="col-md-4">
      <span class="post_form">
        <% if logged_in? %>
        <%= render 'posts/post_form' %>
        <% end %>
      </span>
  </aside>
</div>

app/views/posts/show.html.erb
<body class="show">
  <h1>Peteliškės narvelis</h1>
  <div class="container">
  <div id="show">
    <!-- .to_s is one solution among others to avoid errors if there is no imageny -->
      <%= image_tag @post.picture.url.to_s %>
  </div>
  <div>
    <% if logged_in? %>
      <%= link_to "Ištrinti", @post, method: :delete,
      data: { confirm: "Are you sure?"} %> |
      <%= link_to "Taisyti", edit_post_path(@post) %>
    <% end %>
  </div>
  <section id="information">
  <div class="about">
    <%= simple_format(@post.content) %>
  </div>
  <div>
    <%= @post.price %>
  </div>
</section>
    <ul class="pager">
      <li class="next" id="next">
      <% if @post.next %>
        <%= link_to ">", @post.next %>
        <% end %>
      </li>
        <li class="previous" id="previous">
          <% if @post.previous %>
          <%= link_to "<", @post.previous %>
          <% end %>
        </li>
    </ul>
  </div>
</body>